<?php
/**
 * UPay Global Settings
 *
 * @package WTE_UPay
 */

$wp_travel_engine_settings = get_option( 'wp_travel_engine_settings' );
$upay_client_id     = isset( $wp_travel_engine_settings['upay_settings']['client_id'] ) ? $wp_travel_engine_settings['upay_settings']['client_id'] : '';
$upay_client_secret = isset( $wp_travel_engine_settings['upay_settings']['client_secret'] ) ? $wp_travel_engine_settings['upay_settings']['client_secret'] : '';
$upay_partner_id    = isset( $wp_travel_engine_settings['upay_settings']['partner_id'] ) ? $wp_travel_engine_settings['upay_settings']['partner_id'] : '';
$upay_biller_uuid   = isset( $wp_travel_engine_settings['upay_settings']['biller_uuid'] ) ? $wp_travel_engine_settings['upay_settings']['biller_uuid'] : '';
?>

<div class="wpte-field wpte-checkbox advance-checkbox">
    <label class="wpte-field-label" for="wp_travel_engine_settings[upay_enable]">
        <?php esc_html_e( 'Enable UPay Payment', 'wte-upay' ); ?>
    </label>
    <div class="wpte-checkbox-wrap">
        <input type="checkbox" id="wp_travel_engine_settings[upay_enable]" 
               name="wp_travel_engine_settings[upay_enable]" 
               value="1" 
               <?php checked( ! empty( $wp_travel_engine_settings['upay_enable'] ), true ); ?> />
        <label for="wp_travel_engine_settings[upay_enable]"></label>
    </div>
    <span class="wpte-tooltip"><?php esc_html_e( 'Enable Union Bank UPay payment gateway for trip bookings.', 'wte-upay' ); ?></span>
</div>

<div class="wpte-field wpte-text">
    <label class="wpte-field-label" for="wp_travel_engine_settings[upay_settings][client_id]">
        <?php esc_html_e( 'Client ID (X-IBM-Client-Id)', 'wte-upay' ); ?>
    </label>
    <input type="text" id="wp_travel_engine_settings[upay_settings][client_id]" 
           name="wp_travel_engine_settings[upay_settings][client_id]" 
           value="<?php echo esc_attr( $upay_client_id ); ?>" />
    <span class="wpte-tooltip"><?php esc_html_e( 'Enter your Union Bank UPay Client ID from Developer Portal', 'wte-upay' ); ?></span>
</div>

<div class="wpte-field wpte-password">
    <label class="wpte-field-label" for="wp_travel_engine_settings[upay_settings][client_secret]">
        <?php esc_html_e( 'Client Secret (X-IBM-Client-Secret)', 'wte-upay' ); ?>
    </label>
    <input type="password" id="wp_travel_engine_settings[upay_settings][client_secret]" 
           name="wp_travel_engine_settings[upay_settings][client_secret]" 
           value="<?php echo esc_attr( $upay_client_secret ); ?>" />
    <span class="wpte-tooltip"><?php esc_html_e( 'Enter your Union Bank UPay Client Secret from Developer Portal', 'wte-upay' ); ?></span>
</div>

<div class="wpte-field wpte-text">
    <label class="wpte-field-label" for="wp_travel_engine_settings[upay_settings][partner_id]">
        <?php esc_html_e( 'Partner ID (X-Partner-Id)', 'wte-upay' ); ?>
    </label>
    <input type="text" id="wp_travel_engine_settings[upay_settings][partner_id]" 
           name="wp_travel_engine_settings[upay_settings][partner_id]" 
           value="<?php echo esc_attr( $upay_partner_id ); ?>" />
    <span class="wpte-tooltip"><?php esc_html_e( 'Enter the Partner ID generated by UnionBank', 'wte-upay' ); ?></span>
</div>

<div class="wpte-field wpte-text">
    <label class="wpte-field-label" for="wp_travel_engine_settings[upay_settings][biller_uuid]">
        <?php esc_html_e( 'Biller UUID', 'wte-upay' ); ?>
    </label>
    <input type="text" id="wp_travel_engine_settings[upay_settings][biller_uuid]" 
           name="wp_travel_engine_settings[upay_settings][biller_uuid]" 
           value="<?php echo esc_attr( $upay_biller_uuid ); ?>" />
    <span class="wpte-tooltip"><?php esc_html_e( 'Enter your Biller UUID from UnionBank UPay', 'wte-upay' ); ?></span>
</div>